spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/messdb
spring.datasource.username=yasmin
spring.datasource.password=Rasul@0786

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080